export const metadata = {
  title: 'Reserve | OpenTable',
  description: 'Generated by create next app',
}

export default function SearchLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>{children}</>
  )
}