import RestaurantHeader from '@/app/restaurant/[slug]/_components/RestaurantHeader'
import ReservationCard from '@/app/restaurant/[slug]/_components/ReservationCard'

export const metadata = {
  title: 'Milestones Grill | OpenTable',
  description: 'Generated by create next app',
}

export default function RestaurantLayout({
  children,
  params,
} : {
  children: React.ReactNode
  params: {slug : string}
}) {
  return (
    <>
      <RestaurantHeader name={params.slug} />

      <div className='flex m-auto w-2/3 justify-between items-start 0 -mt-11'>
        {children}
      </div>
    </>
  )
}