import RestaurantHeader from '@/components/RestaurantHeader'
import ReservationCard from '@/components/ReservationCard'

export const metadata = {
  title: 'Milestones Grill | OpenTable',
  description: 'Generated by create next app',
}

export default function RestaurantLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <RestaurantHeader />

      <div className='flex m-auto w-2/3 justify-between items-start 0 -mt-11'>
        {children}
      </div>
    </>
  )
}